### ISSUE TITLE
Kick off a build based on this commit

### ISSUE THREAD

**Issue by nobletrout** [AdoptOpenJDK/openjdk11-upstream-binaries#26]
Looks like the only thing stopping 11.0.15 getting built is running the builder?

https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/commit/9a5e4a4a4d7d90f2a5f42913f1ca398005b7207e

**Comment by jerboaa** [comment]
> Looks like the only thing stopping 11.0.15 getting built is running the builder?
> 
> [9a5e4a4](https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/commit/9a5e4a4a4d7d90f2a5f42913f1ca398005b7207e)

It's in progress. @jhuttana will update the issue once done.

**Comment by jhuttana** [comment]
Now 11.0.15 GA build is made available here: https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases
It will reflect here: https://adoptopenjdk.net/upstream.html?variant=openjdk11&jvmVariant=hotspot in sometime

**Comment by jerboaa** [comment]
Thanks, I think this is done. Feel free to reopen if you disagree.

**Comment by tianon** [comment]
I can't find a commit that caused it (looking through https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/compare/jdk-11.0.14.1+1...jdk-11.0.15+10), but is it intentional that assets on https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/tag/jdk-11.0.14.1%2B1 all consistently start with `OpenJDK11U` and in https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/tag/jdk-11.0.15%2B10 the Windows artifacts start with `OpenJDK11u` instead? (note the change in case on the U)

Looking at the build scripts, it seems like the latter is what it should've always been, but that doesn't really help explain why the former was consistent across Linux/Windows. :sweat_smile:

**Comment by jerboaa** [comment]
@stooke any ideas --^

**Comment by stooke** [comment]
@jerboaa, no, no ideas - I have opened PR #27 that I have submitted to change 11u->11U for the Windows build.
